### ISSUE TITLE
[V] Riepilogo decisioni con contenuto troppo lungo

### ISSUE THREAD

**Issue by TommasoAzz** [qb-team/Stalker-Documentazione#103]
Ove non sia pratico o desiderabile riportare tutto il dettaglio della decisione, al suo posto vi sarà un riferimento tracciabile (e facilmente navigabile per il lettore) verso
una fonte esterna che lo contenga, altrimenti il verbale non potrà svolgere il
suo ruolo.

**Comment by Cis8** [comment]
La tabellina del riepilogo decisioni del verbale del 29 gennaio 2020 non è abbastanza contenuta e comoda?
