### ISSUE TITLE
[NdP] Contenuti che non seguono correttamente la divisione in processi

### ISSUE THREAD

**Issue by TommasoAzz** [qb-team/Stalker-Documentazione#109]
Il vostro documento sembra intuirla, seguendola però
lascamente e in modo diseguale, sia per categorizzazione (talvolta non
conforme) che per nomenclatura, causando confusione informativa.

**Comment by dlazzaro** [comment]
se si riferiva alle due attivita nei processi di supporto che avevno indicato come errate sono state corrette
