### ISSUE TITLE
[NdP] Copertura processi insufficiente

### ISSUE THREAD

**Issue by TommasoAzz** [qb-team/Stalker-Documentazione#110]
La copertura dei processi di nostro interesse è ancora insufficiente, e la loro
attribuzione alle tre categorie principali è arbitraria. La codifica, che voi
promuovete implicitamente a processo, è invece una attività del processo di
sviluppo.

**Comment by dlazzaro** [comment]
la codifica §2.2.5 ora è un'attività del processo di sviluppo §2.2
