### ISSUE TITLE
[NdP] Miglioramenti grafici e rispetto norme

### ISSUE THREAD

**Issue by TommasoAzz** [qb-team/Stalker-Documentazione#142]
Errori grafici

- [x] 2.1.2 elenco puntato da mettere le maiuscole a inizio punto e punto fermo nell'ultimo punto al posto del punto e virgola
- [x] 2.1.4 la frase prima della tabella è centrata
- [x] 2.1.4 la tabella non tutti gli elenchi puntati sono corretti (mancano punti fermi a fine elenco
- [x] 2.1.4.2 punto "Preventivo" c'è scritto "...del progetto; Stalker."
- [x] 2.1.4.3 sempre da ricontrollare l'elenco puntato
- [x] 3.4.3 renderlo elenco puntato
- [x] 4.6.2.2.1 renderlo elenco puntato

**Comment by dlazzaro** [comment]
sistemato tutto chiudo
