### ISSUE TITLE
[NdP] Processi

### ISSUE THREAD

**Issue by TommasoAzz** [qb-team/Stalker-Documentazione#187]
Non è ragionevole che la struttura descrittiva dei processi differisca tra quelli primari e gli altri.

**Comment by dlazzaro** [comment]
per i processi: ognuno deve avere: 
* scopo
* aspettative
* descrizione 
* attività: elenco delle componenti di questo processo.
* metriche 
* strumenti.

**Comment by dlazzaro** [comment]
**ASPETTATIVE** processo di sviluppo: 
The Development Process contains the activities and tasks of the developer. The process contains the
activities for requirements analysis, design, coding, integration, testing, and installation and acceptance
related to software products. It may contain system related activities if stipulated in the contract. The
developer performs or supports the activities in this process in accordance with the contract.
The developer manages the Development Process at the project level following the Management
Process (7.1), which is instantiated in this process; establishes an infrastructure under the process
following the Infrastructure Process (7.2); tailors the process for the project following the Tailoring
Process (annex A); and manages the process at the organizational level following the Improvement
Process (7.3) and the Training Process (7.4). When the developer is the supplier of the developed
software product, the developer performs the Supply Process (5.2).

**ATTIVITA'** raggruppare analisi, progettazione e codifica sotto alla subsection attività, togliere tutti i paragrafi dentro ai 3 elementi sopracitati

**METRICHE** da prendere a pagina 40 del documento e spostare qua.

**STRUMENTI** lasciare quelli elencati

**Comment by dlazzaro** [comment]
3 **PROCESSI ORGANIZZATIVI**
3.1 **GESTIONE DEI PROCESSI**
3.1.1 scopo: da scrivere
3.1.2 prospettive: da scrivere
3.1.3 descrizione: da scrivere
3.1.4 attività:
     3.1.4.1: **inizializzazione e definizione dell'ambito**:  The management process shall be initiated by establishing the requirements of the process to
be undertaken.
 Once the requirements are established, the manager shall establish the feasibility of the
process by checking that the resources (personnel, materials, technology, and environment) required to
execute and manage the process are available, adequate, and appropriate and that the time-scales to
completion are achievable.
 As necessary, and by agreement of all parties concerned, the requirements of the process
may be modified at this point to achieve the completion criteria.  

3.1.4.2 **Pianificazione**: gestione di progetto diventa il planning dello standard, si sposta in questa posizione. la sua sottosezione che si chiama **pianificazione** cambia nome in **strumenti per la pianificazione**

3.1.4.3 **gestione delle comunicazioni** : mettere dentro i due gia esistenti comunicazioni interne ed esterne.  

3.1.4.4  **gestione degli incontri formali** : così com'è eliminando la numerazione interna

3.1.5 **Metriche**

3.1.6 **Strumenti**

**Comment by dlazzaro** [comment]
**processi di supporto**
4.1 **documentazione**
4.1.1 scopo
4.1.2 prospettive: da scrivere
4.1.3 descrizione : The Documentation Process is a process for recording information produced by a life cycle process or activity. The process contains the set of activities, which plan, design, develop, produce, edit, distribute, and maintain those documents needed by all concerned such as managers, engineers, and users of the system or software product.

4.1.4 attività: 
     4.1.4.1: **implementazione del processo**:  dentro ci mettiamo **ciclo di vita**, i tre documenti presenti nella sezione fornitura: studio di fattibilità, piano di progetto e piano di qualifica; aggiungere analisi dei requisiti , verbali e glossario.

   4.1.4.2: **progettazione e sviluppo**: ci mettiamo dentro: **template**, **struttura dei documenti** con tutti i suoi sub-paragraph. 

4.1.5**metriche**: da aggiungere;

4.1.6**Strumenti**: ci vanno i nostri 4.1.5 linguaggi e 4.1.6 strumenti.

**Comment by dlazzaro** [comment]
4.2 **gestione della configurazione**
4.2.1 scopo: è il nostro obiettivo già scritto
4.2.2 prospettive : da scrivere
4.2.3 descrizione: The Configuration Management Process is a process of applying administrative and technical procedures throughout the software life cycle to: identify, define, and baseline software items in a system; control modifications and releases of the items; record and report the status of the items and modification requests; ensure the completeness, consistency, and correctness of the items; and control storage, handling, and delivery of the items.
4.2.4 attività: 
    4.2.4.1 **implementazione del processo**: ci va dentro: **versionamento**.
4.2.5 **metriche** non ce ne sono.    
4.2.6 **Strumenti** ci va dentro: **strumenti di supporto al versionamento**, **repository creati**, **template**, **organizzazione del repository**, **procedura di lavoro collaborativo**; inoltre sono da aggiungere paragrafi su: **Continuos Integration** con travis, configurazione maven, configurazione grandle, sonarQube, registrazione dei video, sito per il manuale manutentore ecc.

**Comment by dlazzaro** [comment]
4.3 **Garanzia della qualità**
4.3.1 scopo: è il nostro obiettivo.
4.3.2 prospettive: da scrivere
4.3.3 descrizione: The Quality Assurance Process is a process for providing adequate assurance that the software products and processes in the project life cycle conform to their specified requirements and adhere to their established plans. To be unbiased, quality assurance needs to have organizational freedom and authority from persons directly responsible for developing the software product or executing the process in the project. Quality assurance may be internal or external depending on whether evidence of product or process quality is demonstrated to the management of the supplier or the acquirer. Quality assurance may make use of the results of other supporting processes, such as Verification, Validation, Joint Reviews, Audits, and Problem Resolution.

4.3.4 **attività**: 
    4.3.4.1**implementazione del processo**
                4.3.4.1.1 **iso 12207**
                4.3.4.1.2 **iso 9126**
   4.3.4.2**garanzie sul prodotto**: 
* It shall be assured that all the plans required by the contract are 
documented, comply with thecontract, are mutually consistent, and are being 
executed as required.  
* It shall be assured that software products and related documentation comply 
with the contract and adhere to the plans. 
* In preparation for the delivery of the software products, it shall be assured 
that they have fully satisfied their contractual requirements and are 
acceptable to the acquirer.

4.3.4.3**garanzie del processo**:
* It shall be assured that those software life cycle processes (supply, development, operation,
maintenance, and supporting processes including quality assurance) employed for the project comply with the contract and adhere to the plans.  
* It should be assured that software product and process measurements are in accordance with
established standards and procedures.  
* It shall be assured that the staff assigned have the skill and knowledge needed to meet the
requirements of the project and receive any necessary training.

**Comment by dlazzaro** [comment]
4.4 **verifica**
4.4.1 scopo: è il nostro obiettivo.
4.4.2 prospettive: da scrivere
4.4.3 descrizione: The Verification Process is a process for determining whether the software products of an activity fulfill the requirements or conditions imposed on them in the previous activities. For cost and performance effectiveness, verification should be integrated, as early as possible, with the process (such as supply, development, operation, or maintenance) that employs it. This process may include analysis, review and test
4.4.4 **attività**: 
**implementazione di processo** e tutto il contenuto si sposta qua senza indicizzazione.
4.4.5 metriche
4.4.6 strumenti

**Comment by dlazzaro** [comment]
4.5 **validazione**
4.5.1 scopo: è il nostro obiettivo.
4.5.2 prospettive: da scrivere
4.5.3 descrizione:The Validation Process is a process for determining whether the requirements and the final, as-built system or software product fulfills its specific intended use. Validation may be conducted in earlier stages. This process may be conducted as a part of Software Acceptance Support
4.5.4 **attività**
**implementazione del processo**: aggiungere i test di accettazione.
4.5.5 metriche
4.5.6 strumenti

**Comment by dlazzaro** [comment]
4.6 **gestione dei cambiamenti**
4.6.1 scopo già presente.
4.6.2 prospettive: da scrivere
4.6.3 descrizione: The Problem Resolution Process is a process for analyzing and resolving the problems (including nonconformances), whatever their nature or source, that are discovered during the execution of development, operation, maintenance, or other processes. The objective is to provide a timely, responsible, and documented means to ensure that all discovered problems are analyzed and resolved and trends are recognized.
4.6.4 **attività**:  4.6.4.1 ** implementazione del processo** già presente
4.6.4.2 **risoluzione del problema** già presente
4.6.5 metriche
4.6.6 strumenti
