### ISSUE TITLE
[AR][UCS1] Autenticazione server

### ISSUE THREAD

**Issue by dlazzaro** [qb-team/Stalker-Documentazione#2]
- [x] **1** Autenticazione al server
- [x] **1.1** Inserimento e-mail
- [x] **1.2** Inserimento password
- [x] **1.3** Password dimenticata
- [x] **1.3.1** Inserimento e-mail
- [x] **1.3.2** E-mail cambio password
- [x] **1.3.3** Nuova password
- [x] **1.3.4** Conferma nuova password
- [x] **1.4** Credenziali errate
- [x] **1.4.5** Pulsante cambio password

**Comment by FraDrago** [comment]
Revisione

**Comment by TommasoAzz** [comment]
@FraDrago ho guardato il tuo UC:
- perché UCS 1.4.5 perde la numerazione ordinata che hai fatto in [questo commit](https://github.com/qb-team/Stalker-Documentazione/commit/b2b45ecd42d3940496da85aa9cfb25139bcef87d)?
- perché c'è un doppio UCS 1.4?
