### ISSUE TITLE
[UCS 3] - metterlo come primo step nel flusso di [UCS 4] [UCS 6] [UCS 7] [UCS 8]

### ISSUE THREAD

**Issue by dlazzaro** [qb-team/Stalker-Documentazione#53]
- [ ] Cambiare i diagrammi UML che raffigurano UCS3 come inclusione;
- [x] Cambiare [UCS 4];
- [x] Cambiare [UCS 6];
- [ ] Cambiare [UCS 7];
- [x] Cambiare [UCS 8];

**Comment by Cis8** [comment]
Ho rimosso UCS 5 poiché non è direttamente collegato a UCS 3, perciò non serve alcuna modifica per esso
