### ISSUE TITLE
[ALL] Fix ai documenti

### ISSUE THREAD

**Issue by dlazzaro** [qb-team/Stalker-Documentazione#63]
- [x] Norme di progetto : cambiare registro modifiche mettendo tutti AMMINISTRATORI tranne @Cis8 e @pheasant98 da segnare come VERIFICATORI 
- [x] Piano di Qualifica: cambiare registro modifiche mettendo @TommasoAzz, @babastreio  e @ChristianMattei come AMMINISTRATORI e @FraDrago e @dlazzaro come VERIFICATORI
- [x] Piano di Progetto: cambiare registro modifiche mettendo @dlazzaro come amministratore @EnricoSalmaso responsabile per l'approvazione, @ChristianMattei @TommasoAzz come verificatori.
- [x] Analisi dei requisiti: ANALISTI @Cis8 @FraDrago  @pheasant98. Poi @babastreio e @EnricoSalmaso come VERIFICATORI e @TommasoAzz come RESPONSABILE per l'approvazione
- [x] Studio di fattibilità: TUTTI analisti tranne @FraDrago segnato come verificatore e @EnricoSalmaso come RESPONSABILE

**Comment by TommasoAzz** [comment]
@babastreio @ChristianMattei discusso oggi
