### ISSUE TITLE
[PDP] Revisione - modifica ortografia, punteggiatura, sintassi [ITALIANO CORRETTO]

### ISSUE THREAD

**Issue by Cis8** [qb-team/Stalker-Documentazione#73]
- Modifica della frase sopra la tabella 5.1.2
- Rimossi punti a fine frase della descrizione del registro delle modifiche
- Rimossi due punti dopo indice delle tabelle e dei diagrammi
- Modificata frase iniziale del punto 1.1, con rimozione e aggiunta di virgole
- Aggiunti due punti dopo "1.6 Scadenze"
- Ridefinita la descrizione dell'analisi dei rischi
- Rivista sintassi di 2.1

**Comment by pheasant98** [comment]
- Tolto \centering dalle tabelle perchè risultava inutile e in alcuni casi creava problemi alla struttura, 
- Sistemata struttura tabella dell'Analisi dei requisiti 6.1
- Modificata la frase riguardante la tabella 5.1.2 e 5.2.2 
- Coretto la parola areogramma 
- Modificata` la frase in ragionamento sugli scostamenti
