### ISSUE TITLE
Modificare nomi dei vari utenti e amministratori tabelle requisiti 

### ISSUE THREAD

**Issue by babastreio** [qb-team/Stalker-Documentazione#77]

**Comment by Cis8** [comment]
Che intendi Riccardo? Cosa dobbiamo modificare? Cosa non va bene?

**Comment by babastreio** [comment]
Se guardi nel piano di qualifica nella sezione test di sistema, abbiamo
specificato che tipo di utente e amministratore compie l'azione. Quindi per
rendere conforme il tutto bisogna specificare l'utente/amministratore anche
nella sezione tabelle dei requisiti (che si trova alla fine del documento
analisi dei requisiti )

Il dom 12 gen 2020, 13:11 Cis8 <notifications@github.com> ha scritto:
